server:
  port: 8085

spring:
  application:
    name: notification-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  mongodb:
    database: bank
    auto-index-creation: true

  config:
    import: optional:file:.env[.properties]